[phases.setup]
nixPkgs = ["python3", "poppler_utils", "gcc", "tesseract-ocr", "tesseract-ocr-eng", "poppler-utils", "libgl1", "libglib2.0-0"]

[phases.install]
cmds = [
  "python3 -m ensurepip --upgrade",
  "python3 -m pip install -r requirements.txt",
  "python3 -m spacy download en_core_web_sm"
]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
