[phases.setup]
nixPkgs = ["python3", "gcc", "tesseract", "poppler_utils", "libGL", "glib"]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  "/opt/venv/bin/pip install --upgrade pip",
  "/opt/venv/bin/pip install -r requirements.txt",
  "/opt/venv/bin/python -m spacy download en_core_web_sm"
]

[start]
cmd = "/opt/venv/bin/uvicorn app.main:app --host 0.0.0.0 --port $PORT"
